apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-vault-backend-secret
  namespace: demo-app
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: demo-vault-backend #Secret-store name 
    kind: SecretStore
  target:
    name: external-secret-v1 #k8s-secret-name
  data:
  - secretKey: k8s-secret1 #k8s-secret-key
    remoteRef:
      key: secret1 #vault-secret-name
      property: secret1_key1 #vault-key-value
  - secretKey: k8s-secret2 #k8s-secret-key
    remoteRef:
      key: secret2  #vault-secret-name
      property: secret2_key2 #vault-key-value