apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: demo-vault-backend
  namespace: demo-app
spec:
  provider:
    vault:
      server: "http://vault.demo-vault:8200"
      path: "demo"
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-read-token"
          key: "token"